### ISSUE TITLE
Is there an update? this isn't running anymore?

### ISSUE THREAD

**Issue by dirkliebich** [asehmi/fastapi-wrapper-apiness#1]

**Comment by asehmi** [comment]
I haven't run this for a while. Can you explain what's happening and show me an error stack trace, please? What versions of Streamlit and FastAPI are you using?

**Comment by asehmi** [comment]
I've updated the app to use the latest FastAPI and Streamlit packages. This required addition of a FastAPI patch for a method that dropped in the new version.
